package com.alone.email;

import java.util.Timer;
import java.util.TimerTask;


public class EmailMainGUI extends javax.swing.JFrame {

    public boolean spam = true;
    
    /**
     * Creates new form EmailMainGUI
     */
    public EmailMainGUI() {
        initComponents();
        
        
    }
    
    private int secondsPassed = 0; // remove this timer nonsense, it was just a test!
    
    public synchronized void spamFunction() {
        
        int spamGap = 20;
        
        Timer spammer = new Timer();
        TimerTask task = new TimerTask() {
            public void run() {
                secondsPassed+=spamGap;
                SendEmail SE1 = new SendEmail(toEmail.getText(), ccEmail.getText(), 
                    "[sent after "+ (secondsPassed) + " seconds] " + 
                            jTextArea1.getText());
            }
        };
        
        spammer.scheduleAtFixedRate(task, spamGap*1000, spamGap*1000);

    }
  
    

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ccEmail = new javax.swing.JTextField();
        toEmail = new javax.swing.JTextField();
        SendButton = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 450));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(52, 152, 219));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 490, 150));

        ccEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ccEmail.setForeground(new java.awt.Color(255, 255, 255));
        ccEmail.setBorder(null);
        ccEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        ccEmail.setOpaque(false);
        ccEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccEmailActionPerformed(evt);
            }
        });
        getContentPane().add(ccEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 490, 30));

        toEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toEmail.setForeground(new java.awt.Color(255, 255, 255));
        toEmail.setBorder(null);
        toEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        toEmail.setOpaque(false);
        toEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toEmailActionPerformed(evt);
            }
        });
        getContentPane().add(toEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 490, 30));

        SendButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SendButtonMouseReleased(evt);
            }
        });
        getContentPane().add(SendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 80, 40));

        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 0, 34, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alone/images/Email_Sender.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseReleased
        System.exit(0);
    }//GEN-LAST:event_CloseMouseReleased

    private void toEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toEmailActionPerformed

    private void ccEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccEmailActionPerformed

    private void SendButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendButtonMouseReleased
        SendEmail SE = new SendEmail(toEmail.getText(), ccEmail.getText(), jTextArea1.getText());
        spam = true;
        spamFunction();
    }//GEN-LAST:event_SendButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel SendButton;
    private javax.swing.JTextField ccEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField toEmail;
    // End of variables declaration//GEN-END:variables
}
